export { Home } from './Home';
export { CollegeExplorer } from './CollegeExplorer';
export { CollegeDetail } from './CollegeDetail';
export { Cutoffs } from './Cutoffs';
export { Eligibility } from './Eligibility';
export { PreferenceSheet } from './PreferenceSheet';
export { Map } from './Map';
export { Rankings } from './Rankings';
export { Documents } from './Documents';
